#!/usr/bin/env python3
"""Fail when the contracts and the command reference diverge; --write regenerates the reference.

The API snapshot and the explicit command mapping must name the same operations, and every
auth-service route a local command uses must exist in the auth contract.
"""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
METHODS = {'get', 'post', 'put', 'patch', 'delete', 'head', 'options'}
EXPECTED_OPERATIONS = 47

# Commands that talk to the auth service or only to local state, with the routes they call.
# `auth.rs` is the source; its contract test pins the same endpoints.
AUTH_COMMANDS = [
    ('voltage login', [('POST', '/api/v1/oauth/device_authorization'), ('POST', '/api/v1/oauth/token'), ('GET', '/api/v1/users/current')]),
    ('voltage logout', [('POST', '/api/v1/oauth/revoke')]),
    ('voltage auth status', []),
    ('voltage auth import-key', []),
    ('voltage organizations list', [('GET', '/api/v1/users/current')]),
    ('voltage environments list', [('POST', '/api/v1/oauth/token'), ('GET', '/api/v1/organizations/{organization_id}/environments')]),
    ('voltage profiles create NAME', []),
    ('voltage profiles get NAME', []),
    ('voltage profiles list', []),
    ('voltage profiles delete NAME', []),
    ('voltage completions SHELL', []),
]
# Commands that use the coinprice service, with the routes they call.
PRICE_COMMANDS = [
    ('voltage price', [('GET', '/currency/{pair}/{time}')]),
    ('voltage convert AMOUNT UNIT --to CURRENCY', [('GET', '/currency/{pair}/{time}')]),
]
AUTH_NOTES = [
    'Every organization API call first exchanges the saved login for an organization token with `POST /api/v1/oauth/token`, and an expiring login is refreshed there as well.',
    'A failed login revokes its new session with `POST /api/v1/oauth/revoke` so nothing is left running on the server.',
]


def operations_in(spec):
    return {
        (method.upper(), path)
        for path, item in spec['paths'].items()
        for method in item
        if method.lower() in METHODS
    }


spec = json.loads((root / 'api/openapi.json').read_text())
auth_spec = json.loads((root / 'api/auth-openapi.json').read_text())
price_spec = json.loads((root / 'api/coinprice-openapi.json').read_text())
registry = json.loads((root / 'api/commands.json').read_text())
operations = {
    value['operationId']: (method.upper(), path)
    for path, item in spec['paths'].items()
    for method, value in item.items()
    if method.lower() in METHODS
}
assert len(operations) == EXPECTED_OPERATIONS, 'Review the contract version and update coverage expectations deliberately'
assert operations.keys() == registry.keys(), f'Missing/extra mappings: {operations.keys() ^ registry.keys()}'
commands = [tuple(v['command']) for v in registry.values()]
assert len(set(commands)) == len(commands), 'Duplicate command mappings'
auth_routes = operations_in(auth_spec)
for command, routes in AUTH_COMMANDS:
    for route in routes:
        assert route in auth_routes, f'{command} uses {route[0]} {route[1]}, which the auth contract does not define'
price_routes = operations_in(price_spec)
for command, routes in PRICE_COMMANDS:
    for route in routes:
        assert route in price_routes, f'{command} uses {route[0]} {route[1]}, which the coinprice contract does not define'

lines = [
    '# Command reference',
    '',
    'Generated by `scripts/check-coverage.py` from the checked-in contracts and the command mapping; do not edit by hand.',
    '',
    '## Login, credentials, and profiles',
    '',
    'These commands use the auth service (`https://auth.voltage.cloud/api/v1`, overridable with `--auth-url`) or only local state.',
    '',
    '| Command | Routes |',
    '|---|---|',
]
for command, routes in AUTH_COMMANDS:
    rendered = '<br>'.join(f'{method} `{path}`' for method, path in routes) or 'local only'
    lines.append(f'| `{command}` | {rendered} |')
lines += ['', *[f'- {note}' for note in AUTH_NOTES], '']
lines += [
    '## Prices',
    '',
    'These commands use the coinprice service (`https://coinprice.voltage.cloud`, overridable with `--price-url`) and need no credentials.',
    '',
    '| Command | Routes |',
    '|---|---|',
]
for command, routes in PRICE_COMMANDS:
    rendered = '<br>'.join(f'{method} `{path}`' for method, path in routes)
    lines.append(f'| `{command}` | {rendered} |')
lines += ['']
lines += [
    '## API operations',
    '',
    'IDs are positional; enclosing scope uses flags. Paths are relative to the API base URL (`https://voltageapi.com/v1`, overridable with `--api-url`).',
    '',
    '| Command | Method | Path |',
    '|---|---|---|',
]
for oid, entry in registry.items():
    method, path = operations[oid]
    name = 'voltage ' + ' '.join(entry['command'])
    if entry.get('target'):
        name += ' ' + entry['target'].upper()
    lines.append(f'| `{name}` | {method} | `{path}` |')
expected = '\n'.join(lines) + '\n'
if '--write' in sys.argv:
    (root / 'docs/commands.md').write_text(expected)
else:
    assert (root / 'docs/commands.md').read_text() == expected, 'Regenerate docs: python3 scripts/check-coverage.py --write'
print(f'{len(operations)} operations mapped uniquely; {len(AUTH_COMMANDS)} auth and local commands and {len(PRICE_COMMANDS)} price commands documented')
