//! Operation contract generated by `build.rs` from the checked-in API snapshot.
//!
//! `api/openapi.json` supplies routes, methods, parameters, and security; `api/commands.json`
//! assigns each operation its command words and positional target. The closed enums below
//! name every alternative those files can express, so behavior keyed on an operation is an
//! exhaustive match rather than a string comparison.

use serde::{Deserialize, Serialize};
use std::sync::LazyLock;

/// Every `operationId` in the checked-in contract.
///
/// Adding an operation to the snapshot requires a variant here; `registry_matches_the_contract`
/// fails until the enum, `api/commands.json`, and the snapshot agree.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[serde(rename_all = "snake_case")]
pub enum OperationId {
    GetAllOrganizationSupportedAssets,
    GetAllOrganizationsWalletsAsUser,
    CreateWallet,
    GetWallet,
    DeleteWallet,
    UpdateWallet,
    GetWalletLedgerAsUser,
    GetWalletPolicies,
    UpdateWalletPolicies,
    GetPayments,
    CreatePayment,
    CreateTreasuryMovement,
    CheckPayment,
    GetPaymentSummary,
    GetWalletPaymentSummary,
    GetPayment,
    GetPaymentHistory,
    UpdateSandboxLineOfCredit,
    GetLineOfCreditSummaryAsUser,
    GetLinesOfCreditSummariesAsUser,
    GetBillAsUser,
    GetBillsAsUser,
    GetBillSummaryAsUser,
    GetWebhooksAsUser,
    CreateWebhook,
    GetWebhook,
    DeleteWebhook,
    UpdateWebhook,
    GenerateWebhookKey,
    TestWebhook,
    StartWebhookAsUser,
    StopWebhookAsUser,
    GetWebhookDeliveriesAsUser,
    GetWebhookDeliverySummaryAsUser,
    GetWebhookDelivery,
    AbandonWebhookDelivery,
    RetryWebhookDelivery,
    GetQuotesAsUser,
    RequestAQuote,
    GetAQuoteAsUser,
    GetEvents,
    CreateEventStreamToken,
    GetSettings,
    UpdateSettings,
    CreateSession,
    GetSession,
    GetSessionAllowedOrigins,
}

impl OperationId {
    /// Every variant, in contract order, for exhaustiveness checks.
    pub const ALL: [Self; 47] = [
        Self::GetAllOrganizationSupportedAssets,
        Self::GetAllOrganizationsWalletsAsUser,
        Self::CreateWallet,
        Self::GetWallet,
        Self::DeleteWallet,
        Self::UpdateWallet,
        Self::GetWalletLedgerAsUser,
        Self::GetWalletPolicies,
        Self::UpdateWalletPolicies,
        Self::GetPayments,
        Self::CreatePayment,
        Self::CreateTreasuryMovement,
        Self::CheckPayment,
        Self::GetPaymentSummary,
        Self::GetWalletPaymentSummary,
        Self::GetPayment,
        Self::GetPaymentHistory,
        Self::UpdateSandboxLineOfCredit,
        Self::GetLineOfCreditSummaryAsUser,
        Self::GetLinesOfCreditSummariesAsUser,
        Self::GetBillAsUser,
        Self::GetBillsAsUser,
        Self::GetBillSummaryAsUser,
        Self::GetWebhooksAsUser,
        Self::CreateWebhook,
        Self::GetWebhook,
        Self::DeleteWebhook,
        Self::UpdateWebhook,
        Self::GenerateWebhookKey,
        Self::TestWebhook,
        Self::StartWebhookAsUser,
        Self::StopWebhookAsUser,
        Self::GetWebhookDeliveriesAsUser,
        Self::GetWebhookDeliverySummaryAsUser,
        Self::GetWebhookDelivery,
        Self::AbandonWebhookDelivery,
        Self::RetryWebhookDelivery,
        Self::GetQuotesAsUser,
        Self::RequestAQuote,
        Self::GetAQuoteAsUser,
        Self::GetEvents,
        Self::CreateEventStreamToken,
        Self::GetSettings,
        Self::UpdateSettings,
        Self::CreateSession,
        Self::GetSession,
        Self::GetSessionAllowedOrigins,
    ];

    /// The response carries a secret that is shown once and never retrievable again.
    pub fn returns_one_time_secret(self) -> bool {
        matches!(
            self,
            Self::CreateWebhook
                | Self::GenerateWebhookKey
                | Self::CreateSession
                | Self::CreateEventStreamToken
        )
    }

    /// The request submits a payment whose acceptance can be reconciled by reading its ID.
    pub fn submits_payment(self) -> bool {
        matches!(self, Self::CreatePayment | Self::CreateTreasuryMovement)
    }

    /// The request or response is a payment that `--wait` can follow to readiness or settlement.
    pub fn supports_wait(self) -> bool {
        self.submits_payment() || self == Self::GetPayment
    }

    /// A ready BOLT11 invoice can be rendered as a QR code or copied to the clipboard.
    pub fn presents_invoice(self) -> bool {
        matches!(self, Self::CreatePayment | Self::GetPayment)
    }

    /// The complete JSON payload must name the wallet it acts on.
    pub fn requires_wallet_in_body(self) -> bool {
        matches!(
            self,
            Self::CreatePayment
                | Self::CreateTreasuryMovement
                | Self::CheckPayment
                | Self::CreateSession
        )
    }

    /// The feature an operation needs regardless of its payload; payments are gated by
    /// their type instead.
    pub fn gated_feature(self) -> Option<GatedFeature> {
        match self {
            Self::CreateTreasuryMovement => Some(GatedFeature::TreasuryMovements),
            _ => None,
        }
    }

    /// The complete JSON payload is a payment request with an explicit ID.
    pub fn takes_payment_payload(self) -> bool {
        matches!(
            self,
            Self::CreatePayment | Self::CreateTreasuryMovement | Self::CheckPayment
        )
    }
}

/// An organization feature Voltage must enable before the API accepts a request; the API
/// rejects other requests with `feature_flag_disabled`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GatedFeature {
    OnChain,
    Bip21,
    TreasuryMovements,
}

impl GatedFeature {
    /// The feature's name in the API's feature flags.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::OnChain => "on_chain",
            Self::Bip21 => "bip21",
            Self::TreasuryMovements => "treasury_movements",
        }
    }
}

/// Credential the API expects for one operation.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum AuthScheme {
    /// An environment API key or an organization token exchanged from a login.
    Account,
    /// One checkout session's bearer token.
    CheckoutSession,
    /// One checkout event stream's query token.
    CheckoutStream,
    /// A public endpoint.
    None,
}

impl AuthScheme {
    /// Checkout credentials come from `--token-file` or an environment variable, never an account.
    pub fn is_checkout(self) -> bool {
        matches!(self, Self::CheckoutSession | Self::CheckoutStream)
    }
}

/// HTTP method of one operation, as the OpenAPI snapshot spells it.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "UPPERCASE")]
pub enum Method {
    Get,
    Post,
    Put,
    Patch,
    Delete,
    Head,
    Options,
}

impl Method {
    /// A read never changes server state, so a failed read is safe to repeat.
    pub fn is_read_only(self) -> bool {
        matches!(self, Self::Get | Self::Head | Self::Options)
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Get => "GET",
            Self::Post => "POST",
            Self::Put => "PUT",
            Self::Patch => "PATCH",
            Self::Delete => "DELETE",
            Self::Head => "HEAD",
            Self::Options => "OPTIONS",
        }
    }
}

impl From<Method> for reqwest::Method {
    fn from(method: Method) -> Self {
        match method {
            Method::Get => Self::GET,
            Method::Post => Self::POST,
            Method::Put => Self::PUT,
            Method::Patch => Self::PATCH,
            Method::Delete => Self::DELETE,
            Method::Head => Self::HEAD,
            Method::Options => Self::OPTIONS,
        }
    }
}

/// Positional resource identifier that names one operation's target.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ResourceTarget {
    WalletId,
    PaymentId,
    WebhookId,
    LineId,
    BillId,
    DeliveryId,
    QuoteId,
    SessionId,
}

impl ResourceTarget {
    /// Placeholder name in the operation path.
    pub fn parameter_name(self) -> &'static str {
        match self {
            Self::WalletId => "wallet_id",
            Self::PaymentId => "payment_id",
            Self::WebhookId => "webhook_id",
            Self::LineId => "line_id",
            Self::BillId => "bill_id",
            Self::DeliveryId => "delivery_id",
            Self::QuoteId => "quote_id",
            Self::SessionId => "session_id",
        }
    }

    /// Placeholder shown in help for the positional argument.
    pub fn value_name(self) -> &'static str {
        match self {
            Self::WalletId => "WALLET_ID",
            Self::PaymentId => "PAYMENT_ID",
            Self::WebhookId => "WEBHOOK_ID",
            Self::LineId => "LINE_ID",
            Self::BillId => "BILL_ID",
            Self::DeliveryId => "DELIVERY_ID",
            Self::QuoteId => "QUOTE_ID",
            Self::SessionId => "SESSION_ID",
        }
    }
}

/// Where the API reads one parameter from.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ParameterLocation {
    Query,
    Path,
    Header,
    Cookie,
}

/// OpenAPI serialization style of one parameter.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
pub enum ParameterStyle {
    Matrix,
    Label,
    Form,
    Simple,
    SpaceDelimited,
    PipeDelimited,
    DeepObject,
}

/// JSON Schema primitive named by a parameter schema's `type`.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum SchemaKind {
    String,
    Number,
    Integer,
    Boolean,
    Object,
    Array,
    Null,
}

/// A parameter schema's `type`, which the snapshot writes as one name or a nullable list.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
#[serde(untagged)]
enum SchemaType {
    One(SchemaKind),
    Many(Vec<SchemaKind>),
}

/// The parts of a parameter schema that decide how a flag value is encoded.
///
/// Composite schemas (`oneOf`, `$ref`) carry no `type` and encode as plain text.
#[derive(Clone, Debug, Default, Deserialize)]
pub struct ParameterSchema {
    #[serde(rename = "type")]
    kind: Option<SchemaType>,
    #[serde(default)]
    items: Option<serde_json::Value>,
}

impl ParameterSchema {
    fn has_kind(&self, kind: SchemaKind) -> bool {
        match &self.kind {
            Some(SchemaType::One(one)) => *one == kind,
            Some(SchemaType::Many(many)) => many.contains(&kind),
            None => false,
        }
    }
}

/// Scope flag that supplies a parameter instead of a generated flag.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ScopeParameter {
    Organization,
    Environment,
    Environments,
    Wallet,
    Webhook,
}

/// One OpenAPI parameter of an operation.
#[derive(Clone, Debug, Deserialize)]
pub struct Parameter {
    pub name: String,
    #[serde(rename = "in")]
    pub location: ParameterLocation,
    #[serde(default)]
    pub schema: ParameterSchema,
    #[serde(default)]
    pub description: String,
    pub style: Option<ParameterStyle>,
    /// Closed set of accepted values from the contract's enum schemas; empty for free text.
    #[serde(default)]
    pub values: Vec<String>,
}

impl Parameter {
    /// The scope flag that supplies this parameter, if it is not a free filter.
    pub fn scope(&self) -> Option<ScopeParameter> {
        match self.name.as_str() {
            "organization_id" => Some(ScopeParameter::Organization),
            "environment_id" => Some(ScopeParameter::Environment),
            "environment_ids" => Some(ScopeParameter::Environments),
            "wallet_id" => Some(ScopeParameter::Wallet),
            "webhook_id" => Some(ScopeParameter::Webhook),
            _ => None,
        }
    }

    /// The checkout stream credential travels as this query parameter and never as a flag.
    pub fn is_credential(&self) -> bool {
        self.name == "stream_token"
    }

    /// A query parameter that the command line can set, through a scope or generated flag.
    pub fn is_query_filter(&self) -> bool {
        self.location == ParameterLocation::Query && !self.is_credential()
    }

    /// Generated long flag for this parameter.
    pub fn flag(&self) -> String {
        query_flag(&self.name)
    }

    pub fn is_boolean(&self) -> bool {
        self.schema.has_kind(SchemaKind::Boolean)
    }

    /// Object parameters encode as `name[key]=value`.
    pub fn is_object(&self) -> bool {
        self.schema.has_kind(SchemaKind::Object) || self.style == Some(ParameterStyle::DeepObject)
    }

    /// Array parameters encode as repeated `name[]=value`, even where the snapshot omits a style.
    pub fn is_array(&self) -> bool {
        self.schema.has_kind(SchemaKind::Array) || self.schema.items.is_some()
    }
}

/// One API operation and the command that reaches it.
#[derive(Clone, Debug, Deserialize)]
pub struct Operation {
    pub id: OperationId,
    pub command: Vec<String>,
    pub target: Option<ResourceTarget>,
    pub method: Method,
    pub path: String,
    pub auth: AuthScheme,
    pub body: bool,
    pub description: String,
    pub parameters: Vec<Parameter>,
}

impl Operation {
    /// The operation is scoped to one environment, through its path or a filter.
    pub fn is_environment_scoped(&self) -> bool {
        self.parameters.iter().any(|parameter| {
            matches!(
                parameter.scope(),
                Some(ScopeParameter::Environment | ScopeParameter::Environments)
            )
        })
    }

    pub fn has_parameter(&self, name: &str) -> bool {
        self.parameters
            .iter()
            .any(|parameter| parameter.name == name)
    }

    /// Query parameters that command-line flags can set.
    pub fn query_filters(&self) -> impl Iterator<Item = &Parameter> {
        self.parameters
            .iter()
            .filter(|parameter| parameter.is_query_filter())
    }

    /// The operation reads or mutates one wallet named by its positional ID.
    pub fn targets_wallet(&self) -> bool {
        self.target == Some(ResourceTarget::WalletId)
    }
}

pub static OPERATIONS: LazyLock<Vec<Operation>> = LazyLock::new(|| {
    serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/operations.json")))
        .expect("generated operation registry")
});

pub fn operation(id: OperationId) -> &'static Operation {
    OPERATIONS
        .iter()
        .find(|operation| operation.id == id)
        .expect("registered operation")
}

/// Long flag name for a documented query parameter.
fn query_flag(name: &str) -> String {
    match name {
        "environment_id" | "environment_ids" => "env".into(),
        "wallet_id" => "wallet".into(),
        "line_of_credit_id" => "credit-line".into(),
        other => other.replace('_', "-"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn registry_matches_the_contract() {
        let ids: BTreeSet<_> = OPERATIONS.iter().map(|operation| operation.id).collect();
        assert_eq!(ids.len(), OPERATIONS.len(), "duplicate operation");
        assert_eq!(ids, OperationId::ALL.into_iter().collect());
        let commands: BTreeSet<_> = OPERATIONS
            .iter()
            .map(|operation| &operation.command)
            .collect();
        assert_eq!(commands.len(), OPERATIONS.len(), "duplicate command");
    }

    #[test]
    fn operation_ids_keep_their_contract_spelling() {
        assert_eq!(
            serde_json::to_value(OperationId::GetAQuoteAsUser).unwrap(),
            "get_a_quote_as_user"
        );
        assert_eq!(
            serde_json::to_value(OperationId::UpdateSandboxLineOfCredit).unwrap(),
            "update_sandbox_line_of_credit"
        );
    }

    #[test]
    fn auth_schemes_follow_the_snapshot_security() {
        assert_eq!(
            operation(OperationId::GetEvents).auth,
            AuthScheme::CheckoutStream
        );
        assert_eq!(
            operation(OperationId::GetSession).auth,
            AuthScheme::CheckoutSession
        );
        assert_eq!(
            operation(OperationId::GetSessionAllowedOrigins).auth,
            AuthScheme::None
        );
        assert_eq!(
            operation(OperationId::CreateEventStreamToken).auth,
            AuthScheme::None
        );
        assert_eq!(operation(OperationId::GetWallet).auth, AuthScheme::Account);
    }

    #[test]
    fn methods_and_targets_keep_their_stable_encodings() {
        assert_eq!(serde_json::to_value(Method::Delete).unwrap(), "DELETE");
        assert_eq!(
            serde_json::to_value(ResourceTarget::LineId).unwrap(),
            "line_id"
        );
        assert_eq!(reqwest::Method::from(Method::Patch), reqwest::Method::PATCH);
        assert!(Method::Get.is_read_only() && !Method::Post.is_read_only());
        for target in [
            ResourceTarget::WalletId,
            ResourceTarget::PaymentId,
            ResourceTarget::WebhookId,
            ResourceTarget::LineId,
            ResourceTarget::BillId,
            ResourceTarget::DeliveryId,
            ResourceTarget::QuoteId,
            ResourceTarget::SessionId,
        ] {
            assert_eq!(target.parameter_name().to_uppercase(), target.value_name());
        }
    }

    #[test]
    fn snapshot_shapes_decide_query_encodings() {
        let payments = operation(OperationId::GetPayments);
        let parameter = |name: &str| payments.parameters.iter().find(|p| p.name == name).unwrap();
        assert!(parameter("metadata").is_object());
        assert!(parameter("statuses").is_array());
        assert!(!parameter("limit").is_array());
        let bills = operation(OperationId::GetBillsAsUser);
        assert!(
            bills
                .parameters
                .iter()
                .any(|p| p.name == "exclude_zero_amount_bills" && p.is_boolean())
        );
        let lines = operation(OperationId::GetLinesOfCreditSummariesAsUser);
        let environments = lines
            .parameters
            .iter()
            .find(|p| p.name == "environment_ids")
            .unwrap();
        assert!(environments.is_array());
        assert_eq!(environments.scope(), Some(ScopeParameter::Environments));
        assert_eq!(environments.flag(), "env");
        let stream = operation(OperationId::GetEvents);
        assert!(stream.parameters.iter().any(Parameter::is_credential));
        assert_eq!(stream.query_filters().count(), 0);
    }

    #[test]
    fn contract_enums_become_closed_value_sets() {
        let payments = operation(OperationId::GetPayments);
        let parameter = |name: &str| payments.parameters.iter().find(|p| p.name == name).unwrap();
        assert_eq!(parameter("sort_order").values, ["ASC", "DESC"]);
        assert_eq!(parameter("direction").values, ["send", "receive"]);
        assert!(
            parameter("statuses")
                .values
                .contains(&"completed".to_string())
        );
        assert!(parameter("limit").values.is_empty());
        assert!(parameter("metadata").values.is_empty());
    }

    #[test]
    fn capability_predicates_name_the_documented_operations() {
        assert!(OperationId::GenerateWebhookKey.returns_one_time_secret());
        assert!(!OperationId::GetWebhook.returns_one_time_secret());
        assert!(
            OperationId::GetPayment.supports_wait() && !OperationId::GetPayment.submits_payment()
        );
        assert!(OperationId::CreateSession.requires_wallet_in_body());
        assert_eq!(
            OperationId::CreateTreasuryMovement.gated_feature(),
            Some(GatedFeature::TreasuryMovements)
        );
        assert_eq!(OperationId::CreatePayment.gated_feature(), None);
        assert_eq!(GatedFeature::OnChain.as_str(), "on_chain");
        assert!(!OperationId::CreateSession.takes_payment_payload());
        assert!(operation(OperationId::GetWalletPolicies).targets_wallet());
        assert!(!operation(OperationId::GetWallet).is_environment_scoped());
        assert!(operation(OperationId::GetPayments).is_environment_scoped());
    }
}
